### ISSUE TITLE
CMakeLists.tmpl not Found

### ISSUE THREAD

**Issue by BioBox** [ARMmbed/mbed-tools#328]
**Describe the bug**
When I install the mbedtools package with `setup.py` it doesn't install the `CMakeLists.tmpl`; I can't find it when doing `pacman -Ql python-mbed-tools`

**To Reproduce**
1. Go to the [aur for mbed-tools](https://aur.archlinux.org/packages/python-mbed-tools)
2. Install the snapshot there (adjust the version number to the newest release!)
3. Run `mbedtools new path`

**Expected behavior**
Create the project.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux

**Additional context**
Here's the stacktrace:

```
Creating a new Mbed program at path '/home/daniel/docs/school/22f/embed/labs/os'.
Downloading mbed-os and adding it to the project.
Traceback (most recent call last):
  File "/usr/bin/mbedtools", line 33, in <module>
    sys.exit(load_entry_point('mbed-tools==0.0.0', 'console_scripts', 'mbedtools')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/mbed_tools/cli/main.py", line 38, in invoke
    super().invoke(context)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/mbed_tools/cli/project_management.py", line 30, in new
    initialise_project(pathlib.Path(path), create_only)
  File "/usr/lib/python3.10/site-packages/mbed_tools/project/project.py", line 49, in initialise_project
    program = MbedProgram.from_new(path)
  File "/usr/lib/python3.10/site-packages/mbed_tools/project/mbed_program.py", line 63, in from_new
    program_files = MbedProgramFiles.from_new(dir_path)
  File "/usr/lib/python3.10/site-packages/mbed_tools/project/_internal/project_data.py", line 87, in from_new
    render_cmakelists_template(cmakelists_file, root_path.stem)
  File "/usr/lib/python3.10/site-packages/mbed_tools/project/_internal/render_templates.py", line 23, in render_cmakelists_template
    render_jinja_template(
  File "/usr/lib/python3.10/site-packages/mbed_tools/project/_internal/render_templates.py", line 55, in render_jinja_template
    template = env.get_template(template_name)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3.10/site-packages/jinja2/loaders.py", line 344, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: CMakeLists.tmpl
```

**Comment by BioBox** [comment]
I fixed this by installing it though pip directly instead of using the AUR. Apoligies!
